### ISSUE TITLE
_TypeError: Null check operator used on a null value in version 0.8.0

### ISSUE THREAD

**Issue by ibraheemalayan** [woltapp/wolt_modal_sheet#279] opened 2024-07-28 08:10 UTC
## Bug report

a null check exception occurred on one of our user's devices ( android )

### Steps to reproduce

Not sure how to reproduce since it occurred on a user's device and was reported by sentry.
But here is the stack trace, it might help you find the issue

> Dart 3.4.4
 Flutter 3.22.3
 Wolt Modal Sheet 0.8.0 ( it also happened in a version with the library of version 0.7.0 about three weeks ago )

<img width="938" alt="Screenshot 2024-07-28 at 11 05 55" src="https://github.com/user-attachments/assets/a25353ce-f831-4e22-ab45-d367ea86e11f">

Raw stacktrace
```
_TypeError: Null check operator used on a null value
  File "framework.dart", line 1223, in State.setState
  File "wolt_modal_sheet_animated_switcher.dart", line 282, in _WoltModalSheetAnimatedSwitcherState._addPage.<fn>
  File "listener_helpers.dart", line 240, in AnimationLocalStatusListenersMixin.notifyStatusListeners
  File "animation_controller.dart", line 841, in AnimationController._checkStatusChanged
  File "animation_controller.dart", line 857, in AnimationController._tick
  File "ticker.dart", line 258, in Ticker._tick
  File "binding.dart", line 1392, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1235, in SchedulerBinding.handleBeginFrame.<fn>
  File "compact_hash.dart", line 633, in _LinkedHashMapMixin.forEach
  File "binding.dart", line 1233, in SchedulerBinding.handleBeginFrame
  File "binding.dart", line 1150, in SchedulerBinding._handleBeginFrame
  File "hooks.dart", line 328, in _invoke1
  File "platform_dispatcher.dart", line 397, in PlatformDispatcher._beginFrame
  File "hooks.dart", line 272, in _beginFrame
```

**Comment by ulusoyca** [comment] 2024-07-28 12:36
@ibraheemalayan How often does this crash happen according to Sentry? Here is a potential fix since it is very difficult to reproduce but I have high level of confidence that I found out the root cause.

**Comment by ibraheemalayan** [comment] 2024-07-28 13:02
@ulusoyca 

We're still in early closed beta so the numbers could be larger when launching, but currently having only few users mostly developers and testers, it happened 3 times in the last month.

It's not common and looks like it doesn't cause a crash, just reported to sentry as an unhandled exception.

**Comment by ulusoyca** [comment] 2024-07-28 13:08
@ibraheemalayan I see. Anyway, it is important to keep the Sentry clean. We can have 8.1.0 release after @TahaTesser reviews my PR.

**Comment by ibraheemalayan** [comment] 2024-08-01 12:22
@ulusoyca 
Any updates ?

**Comment by ulusoyca** [comment] 2024-08-01 12:36
This week we will release 0.9.0 and currently waiting for ReadMe changes. Probably tomorrow or during the weekend.

**Comment by ulusoyca** [comment] 2024-08-01 20:37
> @ulusoyca Any updates ?

Looks like we still need to improve the Readme before the next release. However, the fix is merged to the main branch. Do you think that you can use hash in pubspec?

  wolt_modal_sheet:
    git:
      url: git@github.com:woltapp/wolt_modal_sheet.git
      ref: b3213c33c82c117143ea2fc4a23e41ff87cf8318

**Comment by ulusoyca** [comment] 2024-08-01 20:39
Please don't hesitate to re-open the issue if you see this error in your Sentry logs.

**Closed by ulusoyca** 2024-08-01 20:39 UTC
Labels: bug, in triage, wolt priority, possible hotfix

**Comment by piotruela** [comment] 2025-07-11 10:42
@ulusoyca I've just spotted this issue in my Sentry logs on an app using `wolt_modal_sheet` 0.11.0 version.
Here's the stacktrace:
```
TypeError: Null check operator used on a null value
  #0      State.context (package:flutter/src/widgets/framework.dart:961)
  #1      _WoltModalSheetAnimatedSwitcherState._addPage.<fn> (package:wolt_modal_sheet/src/content/wolt_modal_sheet_animated_switcher.dart:244)
  #2      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:243)
  #3      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:964)
  #4      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:982)
  #5      Ticker._tick (package:flutter/src/scheduler/ticker.dart:277)
  #6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1442)
  #7      SchedulerBinding.handleBeginFrame.<fn> (package:flutter/src/scheduler/binding.dart:1273)
  #8      _LinkedHashMapMixin.forEach (dart:_compact_hash:763)
  #9      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1271)
  #10      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1187)
  #11      _invoke1 (dart:ui/hooks.dart:332)
  #12      PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:410)
  #13      _beginFrame (dart:ui/hooks.dart:277)
```
