### ISSUE TITLE
Set page transition animation duration

### ISSUE THREAD

**Issue by blingkonnerth** [woltapp/wolt_modal_sheet#229] opened 2024-06-06 23:44 UTC
## Bug report

**Describe the bug**
In the documentation is a video, where you can clearly see a page animation transition, where the old page content fades out and the new page fades in. 

I implemented a simple `WoltModalSheet`, but that animation is too fast for me. The fade animation is not even really visible, so I tried setting the `animationDuration`, but no matter to what I set it, nothing changes.

### Steps to reproduce

1. Set `transitionDuration` in `WoltModalSheet`

```
    await WoltModalSheet.show<void>(
      context: context,
      transitionDuration: const Duration(seconds: 3),
```

3. Navigate via `showNext` and `showPrevious`

### Expected behavior

I would expect that the page animation is as long as I set it inside `transitionDuration`.

### Additional Context

I would like to achieve the effect as mentioned in the [doc](https://pub.dev/documentation/wolt_modal_sheet/0.6.0/#usage-of-woltmodalsheet-pages) under **Motion Animation**

**Comment by ulusoyca** [comment] 2024-06-07 06:22
Hi! I think there is a misunderstanding here. `transitionDuration` is used for the modal route, not for in-modal navigation. 

/// The `transitionDuration` argument is used to determine how long it takes
/// for the route to arrive on or leave off the screen. This argument defaults
/// to 200 milliseconds.

I would suggest you to achieve this with WoltModalSheetAnimationStyle example from the ReadMe:

```dart
WoltModalSheetThemeData(
  animationStyle: WoltModalSheetAnimationStyle(
    paginationAnimationStyle: WoltModalSheetPaginationAnimationStyle(
      mainContentIncomingOpacityCurve: const Interval(
        150 / 350,
        350 / 350,
        curve: Curves.linear,
      ),
      modalSheetHeightTransitionCurve: const Interval(
        0 / 350,
        300 / 350,
        curve: Curves.fastOutSlowIn,
      ),
      incomingSabOpacityCurve: const Interval(
        100 / 350,
        300 / 350,
        curve: Curves.linear,
      ),
      // Define additional pagination animation styles as needed.
    ),
    scrollAnimationStyle: WoltModalSheetScrollAnimationStyle(
      heroImageScaleStart: 1.0,
      heroImageScaleEnd: 0.9,
      topBarTitleTranslationYInPixels: 8.0,
      topBarTranslationYInPixels: 4.0,
      // Define additional scroll animation styles as needed.
    ),
  ),
),
```

**Comment by blingkonnerth** [comment] 2024-06-07 07:17
@ulusoyca I thought the same, but when setting the `transitionDuration` lets say to 3 seconds, and I am presenting the sheet with `WoltModalSheet.show`, nothing changes. So I wonder, what `transitionDuratin` is actually doing?

Also, I tried setting the `theme`, but like in your example, I could only find ways to set the `curves`, not the actual `duration`

**Comment by ulusoyca** [comment] 2024-06-10 06:43
> @ulusoyca I thought the same, but when setting the `transitionDuration` lets say to 3 seconds, and I am presenting the sheet with `WoltModalSheet.show`, nothing changes. So I wonder, what `transitionDuratin` is actually doing?
> 
> Also, I tried setting the `theme`, but like in your example, I could only find ways to set the `curves`, not the actual `duration`

Found out the root cause. Working on the fix 👍🏻  Thanks for reporting 🙇🏻

**Comment by auradigitaldev** [comment] 2024-06-19 06:58
> > @ulusoyca I thought the same, but when setting the `transitionDuration` lets say to 3 seconds, and I am presenting the sheet with `WoltModalSheet.show`, nothing changes. So I wonder, what `transitionDuratin` is actually doing?
> > Also, I tried setting the `theme`, but like in your example, I could only find ways to set the `curves`, not the actual `duration`
> 
> Found out the root cause. Working on the fix 👍🏻 Thanks for reporting 🙇🏻

Just to confirm, when you mention the fix, do you mean a fix for being able to control the animation duration only for modal open/close or also for transitions between multi-page modals?

**Comment by ulusoyca** [comment] 2024-06-19 07:13
> a fix for being able to control the animation duration only for modal open/close 

You can check my PR here and add your comment: 
https://github.com/woltapp/wolt_modal_sheet/pull/235

https://github.com/woltapp/wolt_modal_sheet/pull/235/files#diff-15429ba15e752ebb7014b0f6e7043da7e1b7437aed4e09599307eeea3a631b2fR21

**Comment by ulusoyca** [comment] 2024-07-02 00:13
Fixed in https://github.com/woltapp/wolt_modal_sheet/pull/235/files

**Closed by ulusoyca** 2024-07-02 00:13 UTC
Labels: bug, in triage, Custom Modal Type
