### ISSUE TITLE
How can I use Expanded()

### ISSUE THREAD

**Issue by hammamziadeh10** [woltapp/wolt_modal_sheet#124] opened 2024-01-21 19:24 UTC
I'm using a bottom sheet and I have a column. The bottom sheet is set to maxsize (the default 0.9). I'm trying to place some content on the top of the screen and some content on the bottom. How can I achieve that? Using Expanded results in an error. Note: I don't want to use stickyActionBar.

**Comment by Drugjudy** [comment] 2024-01-23 15:29
> I'm using a bottom sheet and I have a column. The bottom sheet is set to maxsize (the default 0.9). I'm trying to place some content on the top of the screen and some content on the bottom. How can I achieve that? Using Expanded results in an error. Note: I don't want to use trailingNabBarWidget.

can you provide some more context? Like code or ss?

**Comment by hammamziadeh10** [comment] 2024-01-25 03:28
I meant without the stickyActionBar (just corrected it). Basically, I used the example given and tried to change page1 (bottom sheet) content to my own content. I set the page settings to forceMaxHeight = true. **I want to place half the content on the top and half on the bottom.**

Here is the problem: I'm using a column and tried to use Expanded() and even Spacer() to separate the content but I get an error. So I assumed that it doesn't work that way.

Please let me know if this is not clear and you need an image/code example.

**Comment by ulusoyca** [comment] 2024-01-25 09:58
@hammamziadeh10 I am aware of the issue. The WoltModalSheet package is designed to have scrollable content by design, and I am working on a PR to support your case. Meanwhile, can you try this:
1. Use SliverModalSheet
2. The non-expanding items should be on top, and wrapper with `SliverToBoxAdapter(child: item.content)`
3. The last item can be Expanded. To achieve this behavior, wrap your child: 
`SliverFillRemaining(hasScrollBody: false, child: widget)`

Please let me know if this workaround helps.

**Comment by ulusoyca** [comment] 2024-01-26 13:31
@hammamziadeh10 Please check this draft PR and let me know if it is useful for you:
https://github.com/woltapp/wolt_modal_sheet/pull/127

**Comment by baqibusiness** [comment] 2024-01-27 23:34
Works great, thanks!

**Comment by hammamziadeh10** [comment] 2024-01-27 23:35
Works great, thanks!

**Comment by ulusoyca** [comment] 2024-01-29 10:31
Fix is merged, and will be released with 0.4.0 this week.

**Closed by ulusoyca** 2024-01-29 10:31 UTC
Labels: good first issue
