### ISSUE TITLE
Wolt Modal Sheet + Go Router + Animations

### ISSUE THREAD

**Issue by schuberty** [woltapp/wolt_modal_sheet#90] opened 2023-10-30 22:02 UTC
I'm currently developing a application that makes use of [GoRouter](https://pub.dev/packages/go_router) for routing and [Animations](https://pub.dev/packages/animations) package for page transitions.

When calling the method `WoltModalSheet.show` with a single `WoltModalSheetPage.withSingleChild` I get the reverse transition of my current page, not showing the page "bellow" it.

<img src="https://github.com/woltapp/wolt_modal_sheet/assets/38429464/2f602062-97b1-491f-84ff-563de6fc12c1" alt="drawing" width="256"/>

Tapping the button "Criar conta" shows the bottom sheet, but it also makes the reverse transition of the page bellow it. I tried some other approaches and reading the source code/examples/documentation but got stuck.

I appreciate any help!

**Comment by ulusoyca** [comment] 2023-10-31 15:24
Hi, 

If you are using GoRouter, I am assuming that you are using Navigator 2.0 and declarative navigation. Do you thing that you can utilize the custom route that this package provide so that instead of imperatively calling the `show` method, update your navigation stack to include the modal sheet. There is an [example](https://github.com/woltapp/wolt_modal_sheet/blob/main/playground_navigator2/lib/router/playground_router_delegate.dart) in the package for this use.

Otherwise, can you please provide a basic reproducible project so that we can debug and find the issue?

**Comment by schuberty** [comment] 2023-11-02 12:48
Hi @ulusoyca, thanks for the response!

I'll try to implement using the example for the navigation 2.0, that one thing I didn't tried, if that doesn't work I'll replicate the code in a fresh project and post here.

**Comment by schuberty** [comment] 2023-11-03 01:08
Hey @ulusoyca, the example using BLoC and other configuration made me a little confused about how to implement it, maybe a more "vanilla" example would be useful for this scenario?

I did a reproducible project with the skeleton template: https://github.com/schuberty/flutter_testing_navigation_2_and_wolts

And got the same behavior when implementation the routing animation, without it, if you undo the comment at line 11 of [shared/go_router](https://github.com/schuberty/flutter_testing_navigation_2_and_wolts/blob/main/lib/src/shared/go_router.dart) and reload it changes to "normal" (without reverse transition animation) behavior.

![untitled](https://github.com/woltapp/wolt_modal_sheet/assets/38429464/209a7543-e5a4-4f5f-bc49-befa0d509c1f)

**Comment by yunusemrebakir** [comment] 2024-03-21 12:09
To help using the package with go_router, we can provide an example app. Since #158 is open, I will close this one and handle adding the example app in that ticket.

**Closed by yunusemrebakir** 2024-03-21 12:09 UTC
