### ISSUE TITLE
Example app remembers last visited page

### ISSUE THREAD

**Issue by jtkeyva** [woltapp/wolt_modal_sheet#57] opened 2023-09-07 07:16 UTC
It remembers the page if you don't X it out or hit close.

Click "Show Modal Sheet"
Click "Next Page"
Swipe down from the top of modal (using the grip) to close modal
Click "Show Modal Sheet"

It will be showing the Next Page of Material Colors.

Or is it a feature?

**Comment by ulusoyca** [comment] 2023-09-07 07:55
It is a small bug in the example app, but not a bug of the package. Thanks for the issue, and please feel free to create a PR.

**Comment by yunusemrebakir** [comment] 2023-09-26 10:15
@jtkeyva We have created a backlog item for this, for that reason I will close this one. Also, feel free to make the fix and send a PR :)

**Closed by yunusemrebakir** 2023-09-26 10:15 UTC

**Comment by kamami** [comment] 2023-11-07 11:53
How can this be fixed? What changes do I need to do in the example app?
