### ISSUE TITLE
List not scrolling properly

### ISSUE THREAD

**Issue by mmotkim** [woltapp/wolt_modal_sheet#102] opened 2023-11-24 04:29 UTC
Hi, loving your package so far because of the easy routes, I've just come across a problem here:
## Bug report
When trying to display a list in a WoltModalSheetPage, either using Single child and ListView.builder or Sliver list and SliverList.builder:

on Android using ListView.builder:  double [GlowingOverscrollIndicator](https://api.flutter.dev/flutter/widgets/GlowingOverscrollIndicator-class.html) when overscrolling on the bottom
on iOS using ListView.builder: The last item of the list keeps being hidden by the list height constraint. It's still there, but when I scroll to the bottom it doesn't show up unless I overscroll. It's like the itemCount misses an item.
It could be worked around by adding bottom padding to the whole list but then empty space would show up on android

on Android using SliverList: The [GlowingOverscrollIndicator](https://api.flutter.dev/flutter/widgets/GlowingOverscrollIndicator-class.html) gets partially hidden by the TopBar
on iOS using SliverList: The scrolling animation is janky, and there's no Overscroll physics and Bouncing physics

Android using ListView.builder: 
![image](https://github.com/woltapp/wolt_modal_sheet/assets/21273828/4430c3d7-500d-4888-b87d-53a41932ecea)

### Steps to reproduce

Using ListView.builder on WoltModalSheetPage.withSingleChild() and SliverList.builder on WoltModalSheetPage.withCustomSliverList with TopBar

---

## Additional context
Flutter 3.13.9
Dart 3.1.5

Tell me if you require additional context or code snippets
---

**Comment by ulusoyca** [comment] 2023-11-24 11:30
Hi @mmotkim Thanks for opening the issue.

> The [GlowingOverscrollIndicator](https://api.flutter.dev/flutter/widgets/GlowingOverscrollIndicator-class.html) gets partially hidden by the TopBar on iOS using SliverList.

This is a bug because the list in the main content is behind the top bar. It is fixed in this [PR] (https://github.com/woltapp/wolt_modal_sheet/pull/104) and will be released in next release.

> There's no Overscroll physics and Bouncing physics

This was a bad design decision we took earlier. [This PR](https://github.com/woltapp/wolt_modal_sheet/pull/103) introduces custom scroll physics and scroll behavior for the main content. The junkiness may happen when you dont use a lazy list.

Unfortunately I am not able to reproduce the double glowing effect in coffee maker example. Here you can see the behavior:

https://github.com/woltapp/wolt_modal_sheet/assets/13782003/9ea9c6d5-41e3-49f8-8331-9396f0f8c0bc

Can you please check the implementation [here](https://github.com/woltapp/wolt_modal_sheet/blob/main/coffee_maker/lib/home/online/modal_pages/ready/offer_recommendation_modal_page.dart).

You should not be able to use `ListView.builder` in pages without a sliver factory constructor, unless you add `shrinkWrap: true` and physics to `NeverScrollablePhysics`. Please check this example of how to use it [here](https://github.com/woltapp/wolt_modal_sheet/blob/main/demo_ui_components/lib/src/selection_list/wolt_selection_list.dart#L126.).

**Comment by ulusoyca** [comment] 2023-12-13 10:08
@mmotkim This is merged and released with 0.2.0 and please let us know if this persists.

**Closed by ulusoyca** 2023-12-13 10:08 UTC
Labels: bug
