### ISSUE TITLE
Sticky Action Bar shadow getting clipped

### ISSUE THREAD

**Issue by mmotkim** [woltapp/wolt_modal_sheet#111] opened 2023-12-04 11:22 UTC
## Bug report
Hi again, I noticed my bottom bar containing a button with shadow keeps getting clipped
This happens with either having the button on the `stickyActionBar` property or just a button on the bottom of `Column`
Is there any ways to fix it without adding padding or margin to the widget itself?

![image](https://github.com/woltapp/wolt_modal_sheet/assets/21273828/e647f362-3016-4af1-8bbe-6c25f09de9ff)

Expected: 
![image](https://github.com/woltapp/wolt_modal_sheet/assets/21273828/29103265-1b22-45f8-b8c8-988225423011)

### Steps to reproduce

My button widget tree:
```
Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
- SizedBox
-  Container - BoxDecoration <- this is where my boxShadow is
-   Material
-    Ink
-     InkWell
-      Text
-       ...

```

## Additional context
Flutter 3.13.9
wolt_modal_sheet 0.1.4

**Comment by ulusoyca** [comment] 2023-12-12 17:21
@mmotkim Thanks for the issue. How would you normally do this in the default bottomsheet of Flutter SDK? The clipped area is the Safe area and I am really not sure whether you can achieve a continuous shadow and blur from content to safe area.

**Comment by mmotkim** [comment] 2023-12-13 10:20
I don't think there's safe area in Flutter's showModalBottomSheet()
I copied (with references fixed) the button code to the builder in showModalBottomSheet and here's the result:
![image](https://github.com/woltapp/wolt_modal_sheet/assets/21273828/9ddc7808-0f36-4da9-87b1-0d43a6e69b50)
Notice I upped the vertical padding a bit so that it doesn't overflow with the black bar in newer iOS UI. The shadow still blends in nicely either.
```
 showModalBottomSheet(
              context: context,
              builder: (context) => Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 28),
                child: AppPositiveButton(
                  title: S.of(context).requests_main_filter_confirm,
                  onPressed: () {
                    print('hi');
                  },
                ),
              ),
            );
```

I've also tried adding `clipBehavior: Clip.none` on various places in my code hierarchy to no avail.

**Comment by ulusoyca** [comment] 2023-12-13 10:22
Got it! Thanks for the input. I will investigate further.

**Comment by ulusoyca** [comment] 2024-01-04 11:03
Hardcoding the safe area color causes issues also in dialogs
![image](https://github.com/woltapp/wolt_modal_sheet/assets/13782003/e395f83c-6b36-4b1a-82c3-81adf068a073)

**Comment by yunusemrebakir** [comment] 2024-03-21 14:28
I reproduced this issue and looking into it 👀

**Comment by yunusemrebakir** [comment] 2024-03-22 11:47
Hey @mmotkim 👋🏽 I looked into this and the cropping is caused by `useSafeArea` property being set to true by default. If you set it to false, it should work as expected. Here is a code piece that demonstrate shadow blends correctly. 
I am closing this issue but if you still have questions feel free to reopen it 👍🏽 

```dart
WoltModalSheet.show<void>(
      pageIndexNotifier: ValueNotifier(0),
      context: context,
      useSafeArea: false,
      pageListBuilder: (modalSheetContext) {
        return [
          WoltModalSheetPage(
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 28),
              child: Container(
                decoration: BoxDecoration(
                  boxShadow: [
                    BoxShadow(
                      color: Colors.red.withOpacity(0.5), // Red shadow color
                      spreadRadius: 18,
                      blurRadius: 4,
                      offset: const Offset(0, 4), // Vertical displacement of the shadow
                    ),
                  ],
                  borderRadius: BorderRadius.circular(4.0), // Button corner radius
                ),
                child: MaterialButton(
                  color: Colors.white, // Button color
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(4.0),
                  ),
                  child: const Text('Show Modal Sheet'),
                  onPressed: () {},
                ),
              ),
            ),
            // child: const SizedBox.shrink(),
          ),
        ];
      },
    );
```

**Closed by yunusemrebakir** 2024-03-22 11:47 UTC
Labels: bug, in triage

**Comment by jkoenig134** [comment] 2024-04-09 17:08
This issue still occurs for me. As a workaround I disable `useSafeArea` in every screen and add a padding with `bottom: MediaQuery.viewInsetsOf(context).bottom`. But I think this is not really how we should use it as there IS this `useSafeArea` option.

**Comment by jkoenig134** [comment] 2024-04-09 17:11
Maybe I just misunderstood the issue of the author, but I'd hope that the SafeArea has the same color as my bottom sheet - but there is a color difference.
