### ISSUE TITLE
Bug with proxy box when open dialog in web

### ISSUE THREAD

**Issue by iyar-avital** [woltapp/wolt_modal_sheet#108] opened 2023-12-03 13:09 UTC
## Bug report

**Describe the bug**

══╡ EXCEPTION CAUGHT BY GESTURES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown while handling a pointer data packet:
Assertion failed:
file:///C:/Users/iyar/Documents/flutter/packages/flutter/lib/src/rendering/proxy_box.dart:2935:12
!debugNeedsLayout
is not true

![image](https://github.com/woltapp/wolt_modal_sheet/assets/57311417/4b4449fe-26cc-4422-af22-aed5adac59cf)
### Steps to reproduce
Open dialog on web using WoltModalSheetPage.withCustomSliverList

### Expected behavior
Without errors:(

---

**Comment by ulusoyca** [comment] 2023-12-07 12:25
Duplicate of https://github.com/woltapp/wolt_modal_sheet/issues/46#issuecomment-1844900317

This is a Flutter issue we are aware of: https://github.com/flutter/flutter/issues/139070

Does this happen when scrolling with trackpad? 

This assertion will only be visible in debug version. You should not see this hit testing reporting in production. We are revamping the internals of the package. Until then, unfortunately, we live with this.

**Closed by ulusoyca** 2023-12-07 12:25 UTC
Labels: bug, in triage
