### ISSUE TITLE
topBarTitle isn't visible

### ISSUE THREAD

**Issue by jnelle** [woltapp/wolt_modal_sheet#43] opened 2023-08-18 15:27 UTC
Hey,

first of all thanks for this great package!

I have encountered an issue with the topBarTitle. I copied the example app [[here](https://github.com/woltapp/wolt_modal_sheet#example-app)](https://github.com/woltapp/wolt_modal_sheet#example-app), but I'm unable to view the topBarTitle as expected. To provide further context, I have attached a screenshot from the widget inspector. The screenshot clearly illustrates that the topBarTitle is not visible.

![2023-08-18 17 25 18](https://github.com/woltapp/wolt_modal_sheet/assets/36324542/c1280b95-a091-4271-bd64-ad3889bb4e60)
![2023-08-18 17 24 35](https://github.com/woltapp/wolt_modal_sheet/assets/36324542/efe729f2-9671-402d-a9ba-b2e3fc9a1538)

**Comment by ulusoyca** [comment] 2023-08-18 17:59
Hi! Are you able to clone the package and run the example apps? Please use this branch:
https://github.com/woltapp/wolt_modal_sheet/pull/42

In the next release (will be very soon) we have a flag (`isTopBarAlwaysVisible`). In your example, did you set `forceMaxHeight` field to true? It is not supposed to fill the screen.

**Comment by buchen** [comment] 2023-08-24 12:21
I can confirm that the example runs from the main branch runs locally.

In my code, the topBarTitle is **not** shown unless I set ```isTopBarLayerAlwaysVisible=true```. If one sets it to false in the example, the the headline is not shown.


BTW, really nice work. Thanks.

**Comment by ulusoyca** [comment] 2023-09-05 13:26
Can you please share your code? @buchen

**Comment by becjit** [comment] 2023-09-07 07:01
@buchen  I faced the same issue with the earlier versions. Looks like it is fixed in the latest one. I tried with 0.1.2. cc @ulusoyca

**Closed** 2023-09-08 06:05 UTC
